# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('screen_name', models.CharField(max_length=120, verbose_name='Screen Name')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Frente')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Bloque')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Candidato')),
                ('frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Frente')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Posici\xf3n')),
            ],
            options={
                'verbose_name': 'Posici\xf3n',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Posicion'),
        ),
        migrations.AddField(
            model_name='lista',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Provincia'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='frente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Frente'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Provincia'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='frente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Frente'),
        ),
    ]
