# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownusers',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
