"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(os.path.join(PROJECT_ROOT, 'src'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r4i^suffk0dushnc#h42%&ahxg1a8!y9j$f!pq@p)65o=myk@i'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
DEBUG = True

#ALLOWED_HOSTS = [
#    'localhost', '127.0.0.1',
#    '104.154.111.244', 'pst-webhost']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'raven.contrib.django.raven_compat',
    'django_celery_results',
    'django_celery_beat',
    'bootstrap3',
    'corecontrol',
    'dashboard',
    'search',
    'control',
    'rest'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'managecenter',
        'USER': 'postgres',
        #'PASSWORD': 'bP9GZY3GXz4ePrPX',
        'PASSWORD': 'gorila38',
        #'HOST': '10.128.0.3',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'rest': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'i4media_phase1',
        'USER': 'postgres',
        #'PASSWORD': 'bP9GZY3GXz4ePrPX',
        'PASSWORD': 'gorila38',
        #'HOST': '10.128.0.3',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # django.contrib.staticfiles.finders.DefaultStorageFinder',
)

BOOTSTRAP3 = {
    'javascript_in_head': True,
    'include_jquery': True,
}

LOGIN_REDIRECT_URL = 'index'

# RAVEN_CONFIG = {
#     'dsn': 'https://4b7210f68ae84d1eb0fd9af389f2e643:57c9720a50bd48fba55bff9f82301c03@sentry.io/204330',
# }

SUIT_CONFIG = {
    'ADMIN_NAME': 'i4Media Suit',
    'MENU_ICONS': {
        'control': 'icon-list-alt',
        'corecontrol': 'icon-cog',
        'search': 'icon-search',
        'auth': 'icon-lock',
    },
}

# CELERY_RESULT_BACKEND = 'django-cache'
# CELERY_BROKER_URL = 'redis://localhost:6379/0'

# SEARCH_REDIS_HOST = '10.128.0.11'